name: first
on: 
  push:
    branches: master
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: job1st1
        run: date
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: job2st1
        run: date
        
  job3:
    name: job3
    runs-on: macos-latest
    steps:
      - name: job3st1
        run: date
        env:
          CODEPASS: ${{secrets.MY_PASS}}
        if: secrets.MY_PASS == '1234'
      - run: |
          then echo "this is code "
#   job4:
#     needs: [job1,job2,job3]
#     name: job4
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkoout
#         uses: actions/checkout@v2
#       - name: setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 17.0.1
#           java-package: jdk
#           architecture: x64
#           distribution: temurin
#       - name: list & version
#         run: | 
#               ls -a
#               java -version
      
