name: first
on: 
  push:
    branches: master
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: job1st1
        uses: actions/checkout@v2.0.0
      - name: job1st2
        run: Env | sort
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: job2st1
        uses: actions/checkout@v2.0.0
      - name: job2st2
        run: "Get-ChildItem Env: Sort-Object Name"
        
